// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Future<FirebaseOptions> get currentPlatform async {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMYshyFHuBKEHOe13VQyi34yNTyH-SRag',
    appId: '1:442590618944:web:ba51c4026efa45ed8446a5',
    messagingSenderId: '442590618944',
    projectId: 'flutter-game-project',
    authDomain: 'flutter-game-project.firebaseapp.com',
    storageBucket: 'flutter-game-project.appspot.com',
    measurementId: 'G-SNY9J0VZ7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbRLXQES1OwP9HP7uyIC6EMEyFY6njTJc',
    appId: '1:442590618944:android:57575250af73d7ce8446a5',
    messagingSenderId: '442590618944',
    projectId: 'flutter-game-project',
    storageBucket: 'flutter-game-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_aY0qbyxhFpa_nPLy0_9_UD4yDhyNhdQ',
    appId: '1:442590618944:ios:0ea715a078732e5e8446a5',
    messagingSenderId: '442590618944',
    projectId: 'flutter-game-project',
    storageBucket: 'flutter-game-project.appspot.com',
    iosBundleId: 'com.example.firstGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_aY0qbyxhFpa_nPLy0_9_UD4yDhyNhdQ',
    appId: '1:442590618944:ios:d9e3d66b5452a18b8446a5',
    messagingSenderId: '442590618944',
    projectId: 'flutter-game-project',
    storageBucket: 'flutter-game-project.appspot.com',
    iosBundleId: 'com.example.firstGame.RunnerTests',
  );
}
